#!/usr/bin/env python3
"""
Generate a local .env file for docker-compose from machine credentials.

Reads:
  ~/.aws/credentials  [ecs] section — Dell ECS S3 keys for IMPACT slides

Usage:
  python3 tools/write_dev_env.py
  docker compose up --build
"""
import argparse
import configparser
import os
import sys
import tempfile
from pathlib import Path


def _write_secure(path: Path, contents: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, temporary = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
    try:
        os.fchmod(fd, 0o600)
        with os.fdopen(fd, "w", encoding="utf-8") as handle:
            handle.write(contents)
        os.replace(temporary, path)
        os.chmod(path, 0o600)
    except Exception:
        try:
            os.close(fd)
        except OSError:
            pass
        try:
            os.unlink(temporary)
        except FileNotFoundError:
            pass
        raise


def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output",
        type=Path,
        default=Path(".env"),
        help="Secure output path (default: .env).",
    )
    args = parser.parse_args(argv)
    aws = configparser.ConfigParser()
    aws.read(os.path.expanduser("~/.aws/credentials"))

    ecs = aws["ecs"] if aws.has_section("ecs") else {}
    if not ecs.get("aws_access_key_id"):
        print("WARNING: no [ecs] section found in ~/.aws/credentials")

    lines = [
        "# Auto-generated by tools/write_dev_env.py — do NOT commit",
        "",
        "# ── Dell ECS (MSK IMPACT slides) — canonical AWS SDK env var names ──",
        f"AWS_ENDPOINT_URL={ecs.get('endpoint_url', 'http://pmindecs.mskcc.org:9020')}",
        f"AWS_ACCESS_KEY_ID={ecs.get('aws_access_key_id', '')}",
        f"AWS_SECRET_ACCESS_KEY={ecs.get('aws_secret_access_key', '')}",
        "",
        "# ── Local dev overrides ───────────────────────────────────────────",
        "MAX_OPEN_SLIDES=8",
        "REDIS_MAXMEMORY=256mb",
        "APP_MEMORY_LIMIT=4g",
        "CORS_ORIGINS=http://localhost:8080,http://localhost:3000",
        "SERVER_PORT=8081",
        "WSI_ALLOWED_SOURCE_SCHEMES=s3,file",
        "WSI_AUTH_AUDIENCE=cbioportal-wsi",
        "WSI_AUTH_MAX_TTL=300",
        f"WSI_AUTH_SECRET={os.environ.get('WSI_AUTH_SECRET', 'local-dev-wsi-secret-change-me-32chars')}",
        f"REDIS_PASSWORD={os.environ.get('REDIS_PASSWORD', 'local-dev-redis-password')}",
        "",
        "# ── Isolated Databricks/S3 WSI namespace for development ───────────",
        "DATABRICKS_CONFIG_PROFILE=dev",
        "DATABRICKS_WAREHOUSE_ID=a52519fa662ce69d",
        "WSI_THUMBNAIL_REGISTRY_TABLE=cdsi_dev.wsi_test.slide_thumbnail_registry",
        "WSI_CANONICAL_ASSOCIATION_TABLE=cdsi_dev.wsi_test.canonical_slide_associations",
        "WSI_SUMMARY_TABLE=cdsi_dev.wsi_test.sample_wsi_summary",
        "THUMBNAIL_ARTIFACT_ROOT_URI=s3://mskmind-bkt/wsi-thumbnails-dev/masters",
        "THUMBNAIL_MANIFEST_URI=s3://mskmind-bkt/wsi-thumbnails-dev/manifest.json",
    ]
    output = args.output.expanduser().resolve()
    _write_secure(output, "\n".join(lines) + "\n")
    print(f"Wrote secure environment file: {output}", file=sys.stderr)


if __name__ == "__main__":
    main()
